# =====================================================================
# HtmlBox —— Gradle 全局属性
# =====================================================================

# JVM 内存与编码（中文注释/中文资源必须指定 UTF-8）
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# 并行与缓存，加快二次构建
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# 使用 AndroidX
android.useAndroidX=true

# 非传递性 R 类，减小体积、加快编译
android.nonTransitiveRClass=true

# Kotlin 官方代码风格
kotlin.code.style=official
